In [58]:
import pandas as pd
import numpy as np
import seaborn as sns
import os

In [59]:
tony_db_2021 = pd.read_csv(r'\\192.168.88.18\oddtech\AIDAILER\byjoinmethod_tony_db2021pluscdr2021.csv')


In [60]:
pd.set_option('display.max_columns',None)

In [61]:
tony_db_2021.head(3)

Unnamed: 0  FullPhoneNumber  cityname state  ZipCode  personexactage  \
0           0       8085360276  Honolulu    HI    96817            61.0   
1           1       8086769544  Honolulu    HI    96818            55.0   
2           2       8084974246  Honolulu    HI    96818            64.0   

   IsMobile estimatedincomecode CreditRating  NumberOfLinesOfCredit  \
0         0                   M            A                   -1.0   
1         0                   O            D                   -1.0   
2         1                   M            F                   -1.0   

   Credit_RangeOfNewCredit  homeownerprobabilitymodel  Disconnected  \
0                     -1.0                        1.0             0   
1                     -1.0                        1.0             0   
2                     -1.0                        1.0             0   

   National DNC  Internal DNC  Litigator             datetime  duration  \
0             0             0          0  2021-08-26 20:40:04         0   
1             0             0          0  2021-08-25 20:59:26         0   
2             0             0          0  2021-08-27 17:48:00         0   

         day  responsive  
0   Thursday           0  
1  Wednesday           0  
2     Friday           0

In [62]:
tony_db_2021.head()

Unnamed: 0  FullPhoneNumber  cityname state  ZipCode  personexactage  \
0           0       8085360276  Honolulu    HI    96817            61.0   
1           1       8086769544  Honolulu    HI    96818            55.0   
2           2       8084974246  Honolulu    HI    96818            64.0   
3           3       8088476778  Honolulu    HI    96819            74.0   
4           4       8088476778  Honolulu    HI    96819            74.0   

   IsMobile estimatedincomecode CreditRating  NumberOfLinesOfCredit  \
0         0                   M            A                   -1.0   
1         0                   O            D                   -1.0   
2         1                   M            F                   -1.0   
3         0                   N            B                   -1.0   
4         0                   N            B                   -1.0   

   Credit_RangeOfNewCredit  homeownerprobabilitymodel  Disconnected  \
0                     -1.0                        1.0             0   
1                     -1.0                        1.0             0   
2                     -1.0                        1.0             0   
3                     -1.0                        1.0             0   
4                     -1.0                        1.0             0   

   National DNC  Internal DNC  Litigator             datetime  duration  \
0             0             0          0  2021-08-26 20:40:04         0   
1             0             0          0  2021-08-25 20:59:26         0   
2             0             0          0  2021-08-27 17:48:00         0   
3             0             0          0  2021-08-27 15:47:52       277   
4             0             0          0  2021-08-24 18:25:34         0   

         day  responsive  
0   Thursday           0  
1  Wednesday           0  
2     Friday           0  
3     Friday           1  
4    Tuesday           0

In [63]:
tony_db_2021['datetime']

0          2021-08-26 20:40:04
1          2021-08-25 20:59:26
2          2021-08-27 17:48:00
3          2021-08-27 15:47:52
4          2021-08-24 18:25:34
                  ...         
1228272    2021-08-17 17:18:14
1228273    2021-04-19 17:50:39
1228274    2021-04-12 17:18:05
1228275    2021-04-01 22:57:05
1228276    2021-04-17 17:03:30
Name: datetime, Length: 1228277, dtype: object

In [110]:
fortrainData = tony_db_2021[['state','personexactage','IsMobile','estimatedincomecode' ,'day', 'duration'], 'datetime']
fortrainData.head()

TypeError: '(['state', 'personexactage', 'IsMobile', 'estimatedincomecode', 'day', 'duration'], 'datetime')' is an invalid key

In [65]:
len(fortrainData.isnull())

1228277

In [66]:
fortrainData = fortrainData[fortrainData['estimatedincomecode'] != 'U']

In [67]:
fortrainData = fortrainData[fortrainData['personexactage'] != 'U']

In [68]:
fortrainData = fortrainData[fortrainData['state'] != 'U']

In [69]:
fortrainData = fortrainData[fortrainData['day'] != 'U']

In [70]:
fortrainData = fortrainData[fortrainData['duration'] != 'U']

In [71]:
fortrainData = fortrainData[fortrainData['IsMobile'] != 'U']

In [72]:
fortrainData.head()

state  personexactage  IsMobile estimatedincomecode        day  duration
0    HI            61.0         0                   M   Thursday         0
1    HI            55.0         0                   O  Wednesday         0
2    HI            64.0         1                   M     Friday         0
3    HI            74.0         0                   N     Friday       277
4    HI            74.0         0                   N    Tuesday         0

In [73]:
fortrainData['personexactage'] = fortrainData['personexactage'].astype(int)

In [74]:
for_model= fortrainData.copy()

# Encoding State

In [75]:
print(fortrainData.groupby('state').size())
print(len(fortrainData.groupby('state')))
print(set(fortrainData['state']))

state
AK       347
AL    106803
AR     33284
AZ     47709
CO     43609
CT     64944
DC     11402
DE     15506
HI       381
IA     56757
ID     22016
KS     33475
KY     59665
ME     22163
MN     37748
MO     84111
MS     41072
MT     17607
ND      8322
NE     20167
NH     17128
NM     19020
NV     31510
OK     37069
OR     42186
RI     19726
SC     57622
SD      8365
TN     76462
UT     28847
WA     54034
WI     73930
WV     25077
WY      5488
dtype: int64
34
{'SC', 'NM', 'OK', 'CO', 'CT', 'KS', 'AL', 'WA', 'AZ', 'WV', 'NE', 'AR', 'DC', 'ND', 'TN', 'WI', 'NH', 'SD', 'ME', 'WY', 'NV', 'MS', 'OR', 'AK', 'ID', 'MO', 'MN', 'DE', 'RI', 'MT', 'UT', 'IA', 'KY', 'HI'}


### Indexing

In [76]:
fortrainData['state'].replace(to_replace = set(fortrainData['state']), value = np.arange(0,34), inplace = True)
fortrainData.groupby('state').size()


state
0      57622
1      19020
2      37069
3      43609
4      64944
5      33475
6     106803
7      54034
8      47709
9      25077
10     20167
11     33284
12     11402
13      8322
14     76462
15     73930
16     17128
17      8365
18     22163
19      5488
20     31510
21     41072
22     42186
23       347
24     22016
25     84111
26     37748
27     15506
28     19726
29     17607
30     28847
31     56757
32     59665
33       381
dtype: int64

### One-hot encoding state column### 

In [77]:
from tensorflow.keras.utils import to_categorical
state_encoded_data = to_categorical(fortrainData['state'])
state_encoded_data


array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

# Encoding Income Data

In [78]:
print(fortrainData.groupby('estimatedincomecode').size())
print(len(fortrainData.groupby('estimatedincomecode')))
print(set(fortrainData['estimatedincomecode']))

estimatedincomecode
A     41257
B    139621
C     54703
D     30354
E     74349
F     32080
G     66151
H     35715
I     68935
J     41435
K     73067
L     49496
M     92943
N    185469
O    145576
P     19019
Q     26774
R     21629
S     24979
dtype: int64
19
{'P', 'I', 'O', 'D', 'C', 'H', 'K', 'N', 'R', 'E', 'B', 'F', 'Q', 'J', 'S', 'A', 'M', 'L', 'G'}


### Indexing Income data

In [79]:
fortrainData['estimatedincomecode'].replace(to_replace = set(fortrainData['estimatedincomecode']), value = np.arange(0,19), inplace = True)
fortrainData.groupby('estimatedincomecode').size()

estimatedincomecode
0      19019
1      68935
2     145576
3      30354
4      54703
5      35715
6      73067
7     185469
8      21629
9      74349
10    139621
11     32080
12     26774
13     41435
14     24979
15     41257
16     92943
17     49496
18     66151
dtype: int64

### One-hot encoding income column

In [80]:
from tensorflow.keras.utils import to_categorical
income_encoded_data = to_categorical(fortrainData['estimatedincomecode'])
income_encoded_data


array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

# Encoding Day Data

In [81]:
print(fortrainData.groupby('day').size())
print(len(fortrainData.groupby('day')))
print(set(fortrainData['day']))

day
Friday       233027
Monday       315966
Saturday      47914
Thursday     243315
Tuesday      221009
Wednesday    162321
dtype: int64
6
{'Saturday', 'Tuesday', 'Monday', 'Wednesday', 'Friday', 'Thursday'}


### Indexing day data

In [82]:
fortrainData['day'].replace(to_replace = set(fortrainData['day']), value = np.arange(0,6), inplace = True)
fortrainData.groupby('day').size()

day
0     47914
1    221009
2    315966
3    162321
4    233027
5    243315
dtype: int64

### One-hot encoding day column

In [83]:
day_encoded_data = to_categorical(fortrainData['day'])
day_encoded_data

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.]], dtype=float32)

In [84]:
day_encoded_data

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.]], dtype=float32)

In [109]:
print(len(state_encoded_data))
print(len(income_encoded_data))
print(len(day_encoded_data))
print(len(fortrainData['personexactage']))
print(len(fortrainData['IsMobile']))

1223552
1223552
1223552
1223552
1223552


In [86]:
state_encoded_data.shape,income_encoded_data.shape, day_encoded_data.shape

((1223552, 34), (1223552, 19), (1223552, 6))

In [108]:
train_data = fortrainData[['personexactage' , 'IsMobile' ,'datetime']]
train_data


KeyError: "['datetime'] not in index"

# SPLITING DATA

In [88]:
from sklearn.model_selection import train_test_split

# Seperating Data "sklearn" buildin Model
X = train_data
# Seperating Variables
y = fortrainData['duration']

# Spliting Data into two type(train, test)
train_X, test_X, train_y, test_y = train_test_split(X, y, random_state = 0)
print('Train Data',train_X,'\n Lenght of train Data', len(train_X))
print('Test Data',test_X,'\n Lenght of Test Data', len(test_X))

Train Data          personexactage  IsMobile
743254               54         0
40455                54         1
1097773              80         0
1226347              67         1
1131754              69         0
...                 ...       ...
361023               41         1
152796               68         0
967057               82         1
118308               69         1
306840               87         0

[917664 rows x 2 columns] 
 Lenght of train Data 917664
Test Data          personexactage  IsMobile
126876               60         1
1163197              82         0
390985               52         1
857330               50         1
108431               70         1
...                 ...       ...
793413               70         1
1161681              82         0
938160               78         1
377433               87         0
896150               37         1

[305888 rows x 2 columns] 
 Lenght of Test Data 305888


In [89]:


# from sklearn.metrics import *
# confusion_matrix(fortrainData['personexactage'].to_list() ,fortrainData['duration'].to_list())

In [90]:
from sklearn.linear_model import LinearRegression

# Using Regression Model
regression = LinearRegression()
regression.fit(train_X, train_y)
print('Model Train')

Model Train


In [91]:
train_X.head()

personexactage  IsMobile
743254               54         0
40455                54         1
1097773              80         0
1226347              67         1
1131754              69         0

In [92]:
train_y.head()

743254       4
40455        0
1097773    201
1226347      9
1131754     12
Name: duration, dtype: int64

In [93]:
def convert(duration):
    if duration <= 9:
        duration = 'D1'
        
    elif duration <=60:
        duration = 'D2'

    else:
        duration = 'D3'
    return duration
fortrainData['duration_classified'] = fortrainData['duration'].apply(convert)


In [94]:
fortrainData

state  personexactage  IsMobile  estimatedincomecode  day  duration  \
0           33              61         0                   16    5         0   
1           33              55         0                    2    3         0   
2           33              64         1                   16    4         0   
3           33              74         0                    7    4       277   
4           33              74         0                    7    1         0   
...        ...             ...       ...                  ...  ...       ...   
1228272     19              63         0                   11    1         0   
1228273     19              63         0                   11    2         0   
1228274     19              63         0                   11    2        21   
1228275     19              63         0                   11    5        20   
1228276     19              40         1                    9    0         0   

        duration_classified  
0                        D1  
1                        D1  
2                        D1  
3                        D3  
4                        D1  
...                     ...  
1228272                  D1  
1228273                  D1  
1228274                  D2  
1228275                  D2  
1228276                  D1  

[1223552 rows x 7 columns]

In [95]:
fortrainData.head()

state  personexactage  IsMobile  estimatedincomecode  day  duration  \
0     33              61         0                   16    5         0   
1     33              55         0                    2    3         0   
2     33              64         1                   16    4         0   
3     33              74         0                    7    4       277   
4     33              74         0                    7    1         0   

  duration_classified  
0                  D1  
1                  D1  
2                  D1  
3                  D3  
4                  D1

# Training the model

In [96]:
# state_encoded_datacolumns =["state"+str(i) for i in range(state_encoded_data.shape[1])]
# day_encoded_datacolumns =["day_"+str(i) for i in range(day_encoded_data.shape[1])]
# income_encoded_datacolumns =["income"+str(i) for i in range(income_encoded_data.shape[1])]

                            
# df_list = [
#             pd.DataFrame(state_encoded_data,columns =state_encoded_datacolumns) ,
#            pd.DataFrame(income_encoded_data, columns = income_encoded_datacolumns), 
#            pd.DataFrame(day_encoded_data, columns=day_encoded_datacolumns)
#           ]

# merged = pd.concat(df_list, axis=1)
# merged.head(2)

In [97]:
from sklearn.model_selection import train_test_split

# Seperating Data "sklearn" buildin Model
X = train_data  
# Seperating Variables
y = fortrainData['duration']

# Spliting Data into two type(train, test)
train_X, test_X, train_y, test_y = train_test_split(X, y, random_state = 0)
print('Train Data',train_X,'\n Lenght of train Data', len(train_X))
print('Test Data',test_X,'\n Lenght of Test Data', len(test_X))

Train Data          personexactage  IsMobile
743254               54         0
40455                54         1
1097773              80         0
1226347              67         1
1131754              69         0
...                 ...       ...
361023               41         1
152796               68         0
967057               82         1
118308               69         1
306840               87         0

[917664 rows x 2 columns] 
 Lenght of train Data 917664
Test Data          personexactage  IsMobile
126876               60         1
1163197              82         0
390985               52         1
857330               50         1
108431               70         1
...                 ...       ...
793413               70         1
1161681              82         0
938160               78         1
377433               87         0
896150               37         1

[305888 rows x 2 columns] 
 Lenght of Test Data 305888


In [98]:
from sklearn.linear_model import LinearRegression

# Using Regression Model
regression = LinearRegression()
regression.fit(train_X, train_y)
print('Model Trained')

Model Trained


In [99]:
pred_test_data = regression.predict(test_X)


In [100]:
pred_test_data

array([14.04777083, 18.50623913, 13.7976258 , ..., 14.61059715,
       18.66257978, 13.32860387])

In [101]:
PredictDataFrame = pd.DataFrame(test_X)
PredictDataFrame


personexactage  IsMobile
126876               60         1
1163197              82         0
390985               52         1
857330               50         1
108431               70         1
...                 ...       ...
793413               70         1
1161681              82         0
938160               78         1
377433               87         0
896150               37         1

[305888 rows x 2 columns]

In [102]:
PredictDataFrame['Actural Duration'] = test_y
PredictDataFrame['Predicted Duration'] = pred_test_data

In [103]:
PredictDataFrame["duration_classified"] = pred_test_data

In [104]:
PredictDataFrame

personexactage  IsMobile  Actural Duration  Predicted Duration  \
126876               60         1                 0           14.047771   
1163197              82         0                28           18.506239   
390985               52         1                 8           13.797626   
857330               50         1                 0           13.735090   
108431               70         1                 0           14.360452   
...                 ...       ...               ...                 ...   
793413               70         1                 0           14.360452   
1161681              82         0                 0           18.506239   
938160               78         1                11           14.610597   
377433               87         0                 0           18.662580   
896150               37         1                 0           13.328604   

         duration_classified  
126876             14.047771  
1163197            18.506239  
390985             13.797626  
857330             13.735090  
108431             14.360452  
...                      ...  
793413             14.360452  
1161681            18.506239  
938160             14.610597  
377433             18.662580  
896150             13.328604  

[305888 rows x 5 columns]

In [105]:

from sklearn.metrics import confusion_matrix
y_true = PredictDataFrame['duration_classified'].values
y_pred = PredictDataFrame['Predicted Duration'].values
confusion_matrix(y_true, y_pred)

ValueError: continuous is not supported